package mod.ke2.init;

import java.util.ArrayList;
import java.util.HashMap;

import mod.ke2.blocks.BlockCarbonite;
import mod.ke2.blocks.BlockDrainBlock;
import mod.ke2.blocks.BlockDrainLily;
import mod.ke2.blocks.BlockGemSeed;
import mod.ke2.blocks.BlockMagicMoss;
import mod.ke2.blocks.BlockMossRose;
import mod.ke2.blocks.BlockWailingStone;
import mod.ke2.blocks.BlockWarpPadCore;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.oredict.OreDictionary;

public class Ke2Blocks {
	public static final HashMap<String, Item> DICTS = new HashMap<String, Item>();
	public static final HashMap<Item, String[]> META = new HashMap<Item, String[]>();
	public static final ArrayList<Item> ITEMS = new ArrayList<Item>();
	
	public static final BlockWailingStone WAILING_STONE = new BlockWailingStone();
	public static final BlockGemSeed GEM_SEED = new BlockGemSeed();
	public static final BlockWarpPadCore WARP_PAD_CORE = new BlockWarpPadCore();
	
	public static final BlockMagicMoss MAGIC_MOSS = new BlockMagicMoss();
	public static final BlockMossRose MOSS_ROSE = new BlockMossRose();
	
	public static final BlockDrainLily VALLEY_DRAIN_LILY = new BlockDrainLily("valley");
	public static final BlockDrainLily DESERT_DRAIN_LILY = new BlockDrainLily("desert");
	public static final BlockDrainLily ALPINE_DRAIN_LILY = new BlockDrainLily("alpine");
	public static final BlockDrainLily NETHER_DRAIN_LILY = new BlockDrainLily("nether");
	
	public static final BlockDrainBlock LIGHT_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(false, "purple", 0);
	public static final BlockDrainBlock BANDED_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(false, "purple", 1);
	public static final BlockDrainBlock DARK_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(false, "purple", 2);
	public static final BlockDrainBlock ERODED_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(true, "purple", 3);
	public static final BlockDrainBlock LIGHT_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(false, "orange", 0);
	public static final BlockDrainBlock BANDED_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(false, "orange", 1);
	public static final BlockDrainBlock DARK_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(false, "orange", 2);
	public static final BlockDrainBlock ERODED_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(true, "orange", 3);
	public static final BlockDrainBlock LIGHT_BLUE_DRAIN_BLOCK = new BlockDrainBlock(false, "blue", 0);
	public static final BlockDrainBlock BANDED_BLUE_DRAIN_BLOCK = new BlockDrainBlock(false, "blue", 1);
	public static final BlockDrainBlock DARK_BLUE_DRAIN_BLOCK = new BlockDrainBlock(false, "blue", 2);
	public static final BlockDrainBlock ERODED_BLUE_DRAIN_BLOCK = new BlockDrainBlock(true, "blue", 3);
	public static final BlockDrainBlock LIGHT_RED_DRAIN_BLOCK = new BlockDrainBlock(false, "red", 0);
	public static final BlockDrainBlock BANDED_RED_DRAIN_BLOCK = new BlockDrainBlock(false, "red", 1);
	public static final BlockDrainBlock DARK_RED_DRAIN_BLOCK = new BlockDrainBlock(false, "red", 2);
	public static final BlockDrainBlock ERODED_RED_DRAIN_BLOCK = new BlockDrainBlock(true, "red", 3);

	public static final BlockCarbonite WHITE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_WHITE);
	public static final BlockCarbonite WHITE_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_WHITE, false);
	public static final BlockCarbonite WHITE_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_WHITE, true);
	public static final BlockCarbonite WHITE_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_WHITE);
	public static final BlockCarbonite WHITE_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_WHITE, false);
	public static final BlockCarbonite WHITE_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_WHITE, true);
	public static final BlockCarbonite ORANGE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_ORANGE);
	public static final BlockCarbonite ORANGE_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_ORANGE, false);
	public static final BlockCarbonite ORANGE_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_ORANGE, true);
	public static final BlockCarbonite ORANGE_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_ORANGE);
	public static final BlockCarbonite ORANGE_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_ORANGE, false);
	public static final BlockCarbonite ORANGE_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_ORANGE, true);
	public static final BlockCarbonite MAGENTA_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_MAGENTA);
	public static final BlockCarbonite MAGENTA_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_MAGENTA, false);
	public static final BlockCarbonite MAGENTA_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_MAGENTA, true);
	public static final BlockCarbonite MAGENTA_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_MAGENTA);
	public static final BlockCarbonite MAGENTA_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_MAGENTA, false);
	public static final BlockCarbonite MAGENTA_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_MAGENTA, true);
	public static final BlockCarbonite LIGHTBLUE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_LIGHTBLUE);
	public static final BlockCarbonite LIGHTBLUE_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_LIGHTBLUE, false);
	public static final BlockCarbonite LIGHTBLUE_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_LIGHTBLUE, true);
	public static final BlockCarbonite LIGHTBLUE_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_LIGHTBLUE);
	public static final BlockCarbonite LIGHTBLUE_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_LIGHTBLUE, false);
	public static final BlockCarbonite LIGHTBLUE_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_LIGHTBLUE, true);
	public static final BlockCarbonite YELLOW_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_YELLOW);
	public static final BlockCarbonite YELLOW_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_YELLOW, false);
	public static final BlockCarbonite YELLOW_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_YELLOW, true);
	public static final BlockCarbonite YELLOW_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_YELLOW);
	public static final BlockCarbonite YELLOW_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_YELLOW, false);
	public static final BlockCarbonite YELLOW_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_YELLOW, true);
	public static final BlockCarbonite LIME_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_LIME);
	public static final BlockCarbonite LIME_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_LIME, false);
	public static final BlockCarbonite LIME_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_LIME, true);
	public static final BlockCarbonite LIME_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_LIME);
	public static final BlockCarbonite LIME_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_LIME, false);
	public static final BlockCarbonite LIME_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_LIME, true);
	public static final BlockCarbonite PINK_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_PINK);
	public static final BlockCarbonite PINK_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_PINK, false);
	public static final BlockCarbonite PINK_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_PINK, true);
	public static final BlockCarbonite PINK_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_PINK);
	public static final BlockCarbonite PINK_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_PINK, false);
	public static final BlockCarbonite PINK_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_PINK, true);
	public static final BlockCarbonite GRAY_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_GRAY);
	public static final BlockCarbonite GRAY_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_GRAY, false);
	public static final BlockCarbonite GRAY_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_GRAY, true);
	public static final BlockCarbonite GRAY_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_GRAY);
	public static final BlockCarbonite GRAY_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_GRAY, false);
	public static final BlockCarbonite GRAY_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_GRAY, true);
	public static final BlockCarbonite SILVER_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_SILVER);
	public static final BlockCarbonite SILVER_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_SILVER, false);
	public static final BlockCarbonite SILVER_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_SILVER, true);
	public static final BlockCarbonite SILVER_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_SILVER);
	public static final BlockCarbonite SILVER_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_SILVER, false);
	public static final BlockCarbonite SILVER_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_SILVER, true);
	public static final BlockCarbonite CYAN_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_CYAN);
	public static final BlockCarbonite CYAN_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_CYAN, false);
	public static final BlockCarbonite CYAN_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_CYAN, true);
	public static final BlockCarbonite CYAN_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_CYAN);
	public static final BlockCarbonite CYAN_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_CYAN, false);
	public static final BlockCarbonite CYAN_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_CYAN, true);
	public static final BlockCarbonite PURPLE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_PURPLE);
	public static final BlockCarbonite PURPLE_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_PURPLE, false);
	public static final BlockCarbonite PURPLE_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_PURPLE, true);
	public static final BlockCarbonite PURPLE_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_PURPLE);
	public static final BlockCarbonite PURPLE_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_PURPLE, false);
	public static final BlockCarbonite PURPLE_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_PURPLE, true);
	public static final BlockCarbonite BLUE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_BLUE);
	public static final BlockCarbonite BLUE_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_BLUE, false);
	public static final BlockCarbonite BLUE_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_BLUE, true);
	public static final BlockCarbonite BLUE_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_BLUE);
	public static final BlockCarbonite BLUE_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_BLUE, false);
	public static final BlockCarbonite BLUE_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_BLUE, true);
	public static final BlockCarbonite BROWN_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_BROWN);
	public static final BlockCarbonite BROWN_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_BROWN, false);
	public static final BlockCarbonite BROWN_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_BROWN, true);
	public static final BlockCarbonite BROWN_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_BROWN);
	public static final BlockCarbonite BROWN_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_BROWN, false);
	public static final BlockCarbonite BROWN_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_BROWN, true);
	public static final BlockCarbonite GREEN_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_GREEN);
	public static final BlockCarbonite GREEN_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_GREEN, false);
	public static final BlockCarbonite GREEN_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_GREEN, true);
	public static final BlockCarbonite GREEN_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_GREEN);
	public static final BlockCarbonite GREEN_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_GREEN, false);
	public static final BlockCarbonite GREEN_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_GREEN, true);
	public static final BlockCarbonite RED_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_RED);
	public static final BlockCarbonite RED_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_RED, false);
	public static final BlockCarbonite RED_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_RED, true);
	public static final BlockCarbonite RED_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_RED);
	public static final BlockCarbonite RED_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_RED, false);
	public static final BlockCarbonite RED_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_RED, true);
	public static final BlockCarbonite BLACK_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.INERT, Ke2Gems.BASIC_BLACK);
	public static final BlockCarbonite BLACK_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_BLACK, false);
	public static final BlockCarbonite BLACK_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.ACTIVE, Ke2Gems.BASIC_BLACK, true);
	public static final BlockCarbonite BLACK_DECORATIVE_CARBONITE = new BlockCarbonite(BlockCarbonite.Variety.DECORATIVE, Ke2Gems.BASIC_BLACK);
	public static final BlockCarbonite BLACK_HOLOGRAPHIC_CARBONITE_OFF = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_BLACK, false);
	public static final BlockCarbonite BLACK_HOLOGRAPHIC_CARBONITE_ON = new BlockCarbonite(BlockCarbonite.Variety.HOLOGRAPHIC, Ke2Gems.BASIC_BLACK, true);
	
	public static void register(RegistryEvent.Register<Block> event) {
		registerBlock(WAILING_STONE, new ResourceLocation("ke2:wailing_stone"), event);
		registerBlock(GEM_SEED, new ResourceLocation("ke2:gem_seed"), event);
		registerBlock(WARP_PAD_CORE, new ResourceLocation("ke2:warp_pad"), event);
		registerBlock(MAGIC_MOSS, new ResourceLocation("ke2:magic_moss"), event);
		registerBlock(MOSS_ROSE, new ResourceLocation("ke2:moss_rose"), event);
		registerBlock(VALLEY_DRAIN_LILY, new ResourceLocation("ke2:valley_drain_lily"), event);
		registerBlock(DESERT_DRAIN_LILY, new ResourceLocation("ke2:desert_drain_lily"), event);
		registerBlock(ALPINE_DRAIN_LILY, new ResourceLocation("ke2:alpine_drain_lily"), event);
		registerBlock(NETHER_DRAIN_LILY, new ResourceLocation("ke2:nether_drain_lily"), event);
		registerBlock(LIGHT_PURPLE_DRAIN_BLOCK, new ResourceLocation("ke2:light_purple_drain_block"), event);
		registerBlock(BANDED_PURPLE_DRAIN_BLOCK, new ResourceLocation("ke2:banded_purple_drain_block"), event);
		registerBlock(DARK_PURPLE_DRAIN_BLOCK, new ResourceLocation("ke2:dark_purple_drain_block"), event);
		registerBlock(ERODED_PURPLE_DRAIN_BLOCK, new ResourceLocation("ke2:eroded_purple_drain_block"), event);
		registerBlock(LIGHT_ORANGE_DRAIN_BLOCK, new ResourceLocation("ke2:light_orange_drain_block"), event);
		registerBlock(BANDED_ORANGE_DRAIN_BLOCK, new ResourceLocation("ke2:banded_orange_drain_block"), event);
		registerBlock(DARK_ORANGE_DRAIN_BLOCK, new ResourceLocation("ke2:dark_orange_drain_block"), event);
		registerBlock(ERODED_ORANGE_DRAIN_BLOCK, new ResourceLocation("ke2:eroded_orange_drain_block"), event);
		registerBlock(LIGHT_BLUE_DRAIN_BLOCK, new ResourceLocation("ke2:light_blue_drain_block"), event);
		registerBlock(BANDED_BLUE_DRAIN_BLOCK, new ResourceLocation("ke2:banded_blue_drain_block"), event);
		registerBlock(DARK_BLUE_DRAIN_BLOCK, new ResourceLocation("ke2:dark_blue_drain_block"), event);
		registerBlock(ERODED_BLUE_DRAIN_BLOCK, new ResourceLocation("ke2:eroded_blue_drain_block"), event);
		registerBlock(LIGHT_RED_DRAIN_BLOCK, new ResourceLocation("ke2:light_red_drain_block"), event);
		registerBlock(BANDED_RED_DRAIN_BLOCK, new ResourceLocation("ke2:banded_red_drain_block"), event);
		registerBlock(DARK_RED_DRAIN_BLOCK, new ResourceLocation("ke2:dark_red_drain_block"), event);
		registerBlock(ERODED_RED_DRAIN_BLOCK, new ResourceLocation("ke2:eroded_red_drain_block"), event);
		registerBlock(WHITE_CARBONITE, new ResourceLocation("ke2:white_carbonite"), event);
		registerBlock(WHITE_CARBONITE_OFF, new ResourceLocation("ke2:white_carbonite_off"), event);
		registerBlock(WHITE_CARBONITE_ON, new ResourceLocation("ke2:white_carbonite_on"), event);
		registerBlock(WHITE_DECORATIVE_CARBONITE, new ResourceLocation("ke2:white_decorative_carbonite"), event);
		registerBlock(WHITE_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:white_holographic_carbonite_off"), event);
		registerBlock(WHITE_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:white_holographic_carbonite_on"), event);
		registerBlock(ORANGE_CARBONITE, new ResourceLocation("ke2:orange_carbonite"), event);
		registerBlock(ORANGE_CARBONITE_OFF, new ResourceLocation("ke2:orange_carbonite_off"), event);
		registerBlock(ORANGE_CARBONITE_ON, new ResourceLocation("ke2:orange_carbonite_on"), event);
		registerBlock(ORANGE_DECORATIVE_CARBONITE, new ResourceLocation("ke2:orange_decorative_carbonite"), event);
		registerBlock(ORANGE_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:orange_holographic_carbonite_off"), event);
		registerBlock(ORANGE_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:orange_holographic_carbonite_on"), event);
		registerBlock(MAGENTA_CARBONITE, new ResourceLocation("ke2:magenta_carbonite"), event);
		registerBlock(MAGENTA_CARBONITE_OFF, new ResourceLocation("ke2:magenta_carbonite_off"), event);
		registerBlock(MAGENTA_CARBONITE_ON, new ResourceLocation("ke2:magenta_carbonite_on"), event);
		registerBlock(MAGENTA_DECORATIVE_CARBONITE, new ResourceLocation("ke2:magenta_decorative_carbonite"), event);
		registerBlock(MAGENTA_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:magenta_holographic_carbonite_off"), event);
		registerBlock(MAGENTA_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:magenta_holographic_carbonite_on"), event);
		registerBlock(LIGHTBLUE_CARBONITE, new ResourceLocation("ke2:lightblue_carbonite"), event);
		registerBlock(LIGHTBLUE_CARBONITE_OFF, new ResourceLocation("ke2:lightblue_carbonite_off"), event);
		registerBlock(LIGHTBLUE_CARBONITE_ON, new ResourceLocation("ke2:lightblue_carbonite_on"), event);
		registerBlock(LIGHTBLUE_DECORATIVE_CARBONITE, new ResourceLocation("ke2:lightblue_decorative_carbonite"), event);
		registerBlock(LIGHTBLUE_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:lightblue_holographic_carbonite_off"), event);
		registerBlock(LIGHTBLUE_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:lightblue_holographic_carbonite_on"), event);
		registerBlock(YELLOW_CARBONITE, new ResourceLocation("ke2:yellow_carbonite"), event);
		registerBlock(YELLOW_CARBONITE_OFF, new ResourceLocation("ke2:yellow_carbonite_off"), event);
		registerBlock(YELLOW_CARBONITE_ON, new ResourceLocation("ke2:yellow_carbonite_on"), event);
		registerBlock(YELLOW_DECORATIVE_CARBONITE, new ResourceLocation("ke2:yellow_decorative_carbonite"), event);
		registerBlock(YELLOW_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:yellow_holographic_carbonite_off"), event);
		registerBlock(YELLOW_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:yellow_holographic_carbonite_on"), event);
		registerBlock(LIME_CARBONITE, new ResourceLocation("ke2:lime_carbonite"), event);
		registerBlock(LIME_CARBONITE_OFF, new ResourceLocation("ke2:lime_carbonite_off"), event);
		registerBlock(LIME_CARBONITE_ON, new ResourceLocation("ke2:lime_carbonite_on"), event);
		registerBlock(LIME_DECORATIVE_CARBONITE, new ResourceLocation("ke2:lime_decorative_carbonite"), event);
		registerBlock(LIME_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:lime_holographic_carbonite_off"), event);
		registerBlock(LIME_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:lime_holographic_carbonite_on"), event);
		registerBlock(PINK_CARBONITE, new ResourceLocation("ke2:pink_carbonite"), event);
		registerBlock(PINK_CARBONITE_OFF, new ResourceLocation("ke2:pink_carbonite_off"), event);
		registerBlock(PINK_CARBONITE_ON, new ResourceLocation("ke2:pink_carbonite_on"), event);
		registerBlock(PINK_DECORATIVE_CARBONITE, new ResourceLocation("ke2:pink_decorative_carbonite"), event);
		registerBlock(PINK_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:pink_holographic_carbonite_off"), event);
		registerBlock(PINK_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:pink_holographic_carbonite_on"), event);
		registerBlock(GRAY_CARBONITE, new ResourceLocation("ke2:gray_carbonite"), event);
		registerBlock(GRAY_CARBONITE_OFF, new ResourceLocation("ke2:gray_carbonite_off"), event);
		registerBlock(GRAY_CARBONITE_ON, new ResourceLocation("ke2:gray_carbonite_on"), event);
		registerBlock(GRAY_DECORATIVE_CARBONITE, new ResourceLocation("ke2:gray_decorative_carbonite"), event);
		registerBlock(GRAY_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:gray_holographic_carbonite_off"), event);
		registerBlock(GRAY_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:gray_holographic_carbonite_on"), event);
		registerBlock(SILVER_CARBONITE, new ResourceLocation("ke2:silver_carbonite"), event);
		registerBlock(SILVER_CARBONITE_OFF, new ResourceLocation("ke2:silver_carbonite_off"), event);
		registerBlock(SILVER_CARBONITE_ON, new ResourceLocation("ke2:silver_carbonite_on"), event);
		registerBlock(SILVER_DECORATIVE_CARBONITE, new ResourceLocation("ke2:silver_decorative_carbonite"), event);
		registerBlock(SILVER_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:silver_holographic_carbonite_off"), event);
		registerBlock(SILVER_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:silver_holographic_carbonite_on"), event);
		registerBlock(CYAN_CARBONITE, new ResourceLocation("ke2:cyan_carbonite"), event);
		registerBlock(CYAN_CARBONITE_OFF, new ResourceLocation("ke2:cyan_carbonite_off"), event);
		registerBlock(CYAN_CARBONITE_ON, new ResourceLocation("ke2:cyan_carbonite_on"), event);
		registerBlock(CYAN_DECORATIVE_CARBONITE, new ResourceLocation("ke2:cyan_decorative_carbonite"), event);
		registerBlock(CYAN_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:cyan_holographic_carbonite_off"), event);
		registerBlock(CYAN_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:cyan_holographic_carbonite_on"), event);
		registerBlock(PURPLE_CARBONITE, new ResourceLocation("ke2:purple_carbonite"), event);
		registerBlock(PURPLE_CARBONITE_OFF, new ResourceLocation("ke2:purple_carbonite_off"), event);
		registerBlock(PURPLE_CARBONITE_ON, new ResourceLocation("ke2:purple_carbonite_on"), event);
		registerBlock(PURPLE_DECORATIVE_CARBONITE, new ResourceLocation("ke2:purple_decorative_carbonite"), event);
		registerBlock(PURPLE_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:purple_holographic_carbonite_off"), event);
		registerBlock(PURPLE_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:purple_holographic_carbonite_on"), event);
		registerBlock(BLUE_CARBONITE, new ResourceLocation("ke2:blue_carbonite"), event);
		registerBlock(BLUE_CARBONITE_OFF, new ResourceLocation("ke2:blue_carbonite_off"), event);
		registerBlock(BLUE_CARBONITE_ON, new ResourceLocation("ke2:blue_carbonite_on"), event);
		registerBlock(BLUE_DECORATIVE_CARBONITE, new ResourceLocation("ke2:blue_decorative_carbonite"), event);
		registerBlock(BLUE_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:blue_holographic_carbonite_off"), event);
		registerBlock(BLUE_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:blue_holographic_carbonite_on"), event);
		registerBlock(BROWN_CARBONITE, new ResourceLocation("ke2:brown_carbonite"), event);
		registerBlock(BROWN_CARBONITE_OFF, new ResourceLocation("ke2:brown_carbonite_off"), event);
		registerBlock(BROWN_CARBONITE_ON, new ResourceLocation("ke2:brown_carbonite_on"), event);
		registerBlock(BROWN_DECORATIVE_CARBONITE, new ResourceLocation("ke2:brown_decorative_carbonite"), event);
		registerBlock(BROWN_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:brown_holographic_carbonite_off"), event);
		registerBlock(BROWN_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:brown_holographic_carbonite_on"), event);
		registerBlock(GREEN_CARBONITE, new ResourceLocation("ke2:green_carbonite"), event);
		registerBlock(GREEN_CARBONITE_OFF, new ResourceLocation("ke2:green_carbonite_off"), event);
		registerBlock(GREEN_CARBONITE_ON, new ResourceLocation("ke2:green_carbonite_on"), event);
		registerBlock(GREEN_DECORATIVE_CARBONITE, new ResourceLocation("ke2:green_decorative_carbonite"), event);
		registerBlock(GREEN_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:green_holographic_carbonite_off"), event);
		registerBlock(GREEN_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:green_holographic_carbonite_on"), event);
		registerBlock(RED_CARBONITE, new ResourceLocation("ke2:red_carbonite"), event);
		registerBlock(RED_CARBONITE_OFF, new ResourceLocation("ke2:red_carbonite_off"), event);
		registerBlock(RED_CARBONITE_ON, new ResourceLocation("ke2:red_carbonite_on"), event);
		registerBlock(RED_DECORATIVE_CARBONITE, new ResourceLocation("ke2:red_decorative_carbonite"), event);
		registerBlock(RED_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:red_holographic_carbonite_off"), event);
		registerBlock(RED_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:red_holographic_carbonite_on"), event);
		registerBlock(BLACK_CARBONITE, new ResourceLocation("ke2:black_carbonite"), event);
		registerBlock(BLACK_CARBONITE_OFF, new ResourceLocation("ke2:black_carbonite_off"), event);
		registerBlock(BLACK_CARBONITE_ON, new ResourceLocation("ke2:black_carbonite_on"), event);
		registerBlock(BLACK_DECORATIVE_CARBONITE, new ResourceLocation("ke2:black_decorative_carbonite"), event);
		registerBlock(BLACK_HOLOGRAPHIC_CARBONITE_OFF, new ResourceLocation("ke2:black_holographic_carbonite_off"), event);
		registerBlock(BLACK_HOLOGRAPHIC_CARBONITE_ON, new ResourceLocation("ke2:black_holographic_carbonite_on"), event);
	}
	public static void registerOre(Block block, ResourceLocation location, RegistryEvent.Register<Block> event, String... ores) {
		registerBlock(block, location, event);
		for (int i = 0; i < ores.length; ++i) {
			OreDictionary.registerOre(ores[i], ITEMS.get(ITEMS.size() - 1));
		}
	}
	public static void registerBlock(Block block, ResourceLocation location, RegistryEvent.Register<Block> event, String...meta) {
		event.getRegistry().register(block.setRegistryName(location));
		ITEMS.add(new ItemBlock(block).setRegistryName(location));
	}
}