package mod.ke2.init;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent;

public class Ke2Sounds {
	public static final SoundEvent WAILING_STONE = new SoundEvent(new ResourceLocation("ke2:block.wailing_stone"));
	public static final SoundEvent DESTABILIZER = new SoundEvent(new ResourceLocation("ke2:item.destabilizer"));
	public static final SoundEvent BUBBLE_CREATE = new SoundEvent(new ResourceLocation("ke2:entity.bubble.create"));
	public static final SoundEvent BUBBLE_POP = new SoundEvent(new ResourceLocation("ke2:entity.bubble.pop"));
	public static final SoundEvent BUBBLE_SEND = new SoundEvent(new ResourceLocation("ke2:entity.bubble.send"));
	public static final SoundEvent MISC_GEM_BURST = new SoundEvent(new ResourceLocation("ke2:entity.misc.gem_burst"));
	public static final SoundEvent MECH_ROBONOID = new SoundEvent(new ResourceLocation("ke2:entity.mech.robonoid"));
	public static final SoundEvent MECH_PRISM = new SoundEvent(new ResourceLocation("ke2:entity.mech.prism"));
	public static final SoundEvent GEM_GENERIC = new SoundEvent(new ResourceLocation("ke2:entity.gem.generic"));
	public static final SoundEvent GEM_AGATE = new SoundEvent(new ResourceLocation("ke2:entity.gem.agate"));
	public static final SoundEvent GEM_AMETHYST = new SoundEvent(new ResourceLocation("ke2:entity.gem.amethyst"));
	public static final SoundEvent GEM_AQUA_AURA_QUARTZ = new SoundEvent(new ResourceLocation("ke2:entity.gem.aqua_aura_quartz"));
	public static final SoundEvent GEM_AQUAMARINE = new SoundEvent(new ResourceLocation("ke2:entity.gem.aquamarine"));
	public static final SoundEvent GEM_BISMUTH = new SoundEvent(new ResourceLocation("ke2:entity.gem.bismuth"));
	public static final SoundEvent GEM_BLUE_DIAMOND = new SoundEvent(new ResourceLocation("ke2:entity.gem.blue_diamond"));
	public static final SoundEvent GEM_CARNELIAN = new SoundEvent(new ResourceLocation("ke2:entity.gem.carnelian"));
	public static final SoundEvent GEM_CITRINE = new SoundEvent(new ResourceLocation("ke2:entity.gem.citrine"));
	public static final SoundEvent GEM_CLUSTER = new SoundEvent(new ResourceLocation("ke2:entity.gem.cluster"));
	public static final SoundEvent GEM_CORAL = new SoundEvent(new ResourceLocation("ke2:entity.gem.coral"));
	public static final SoundEvent GEM_DEMANTOID = new SoundEvent(new ResourceLocation("ke2:entity.gem.demantoid"));
	public static final SoundEvent GEM_DESERT_GLASS = new SoundEvent(new ResourceLocation("ke2:entity.gem.desert_glass"));
	public static final SoundEvent GEM_EMERALD = new SoundEvent(new ResourceLocation("ke2:entity.gem.emerald"));
	public static final SoundEvent GEM_ENDER_PEARL = new SoundEvent(new ResourceLocation("ke2:entity.gem.ender_pearl"));
	public static final SoundEvent GEM_HESSONITE = new SoundEvent(new ResourceLocation("ke2:entity.gem.hessonite"));
	public static final SoundEvent GEM_HIDDENITE = new SoundEvent(new ResourceLocation("ke2:entity.gem.hiddenite"));
	public static final SoundEvent GEM_JADE = new SoundEvent(new ResourceLocation("ke2:entity.gem.jade"));
	public static final SoundEvent GEM_JASPER = new SoundEvent(new ResourceLocation("ke2:entity.gem.jasper"));
	public static final SoundEvent GEM_KUNZITE = new SoundEvent(new ResourceLocation("ke2:entity.gem.kunzite"));
	public static final SoundEvent GEM_LAPIS_LAZULI = new SoundEvent(new ResourceLocation("ke2:entity.gem.lapis_lazuli"));
	public static final SoundEvent GEM_LARIMAR = new SoundEvent(new ResourceLocation("ke2:entity.gem.larimar"));
	public static final SoundEvent GEM_MELANITE = new SoundEvent(new ResourceLocation("ke2:entity.gem.melanite"));
	public static final SoundEvent GEM_MOTHER_OF_PEARL = new SoundEvent(new ResourceLocation("ke2:entity.gem.mother_of_pearl"));
	public static final SoundEvent GEM_NEPHRITE = new SoundEvent(new ResourceLocation("ke2:entity.gem.nephrite"));
	public static final SoundEvent GEM_PEARL = new SoundEvent(new ResourceLocation("ke2:entity.gem.pearl"));
	public static final SoundEvent GEM_PEBBLE = new SoundEvent(new ResourceLocation("ke2:entity.gem.pebble"));
	public static final SoundEvent GEM_PERIDOT = new SoundEvent(new ResourceLocation("ke2:entity.gem.peridot"));
	public static final SoundEvent GEM_PINK_DIAMOND = new SoundEvent(new ResourceLocation("ke2:entity.gem.pink_diamond"));
	public static final SoundEvent GEM_PYRITE = new SoundEvent(new ResourceLocation("ke2:entity.gem.pyrite"));
	public static final SoundEvent GEM_PYROPE = new SoundEvent(new ResourceLocation("ke2:entity.gem.pyrope"));
	public static final SoundEvent GEM_ROSE_QUARTZ = new SoundEvent(new ResourceLocation("ke2:entity.gem.rose_quartz"));
	public static final SoundEvent GEM_RUBY = new SoundEvent(new ResourceLocation("ke2:entity.gem.ruby"));
	public static final SoundEvent GEM_RUTILE = new SoundEvent(new ResourceLocation("ke2:entity.gem.rutile"));
	public static final SoundEvent GEM_SAPPHIRE = new SoundEvent(new ResourceLocation("ke2:entity.gem.sapphire"));
	public static final SoundEvent GEM_SNOWFLAKE_OBSIDIAN = new SoundEvent(new ResourceLocation("ke2:entity.gem.snowflake_obsidian"));
	public static final SoundEvent GEM_TOPAZ = new SoundEvent(new ResourceLocation("ke2:entity.gem.topaz"));
	public static final SoundEvent GEM_WATERMELON_TOURMALINE = new SoundEvent(new ResourceLocation("ke2:entity.gem.watermelon_tourmaline"));
	public static final SoundEvent GEM_WHITE_DIAMOND = new SoundEvent(new ResourceLocation("ke2:entity.gem.white_diamond"));
	public static final SoundEvent GEM_YELLOW_DIAMOND = new SoundEvent(new ResourceLocation("ke2:entity.gem.yellow_diamond"));
	public static final SoundEvent GEM_ZIRCON = new SoundEvent(new ResourceLocation("ke2:entity.gem.zircon"));

	public static void register(RegistryEvent.Register<SoundEvent> event) {
		Ke2Sounds.registerSound(Ke2Sounds.WAILING_STONE, new ResourceLocation("ke2:block.wailing_stone"), event);
		Ke2Sounds.registerSound(Ke2Sounds.DESTABILIZER, new ResourceLocation("ke2:item.destabilizer"), event);
		Ke2Sounds.registerSound(Ke2Sounds.BUBBLE_CREATE, new ResourceLocation("ke2:entity.bubble.create"), event);
		Ke2Sounds.registerSound(Ke2Sounds.BUBBLE_POP, new ResourceLocation("ke2:entity.bubble.pop"), event);
		Ke2Sounds.registerSound(Ke2Sounds.BUBBLE_SEND, new ResourceLocation("ke2:entity.bubble.send"), event);
		Ke2Sounds.registerSound(Ke2Sounds.MISC_GEM_BURST, new ResourceLocation("ke2:entity.misc.gem_burst"), event);
		Ke2Sounds.registerSound(Ke2Sounds.MECH_ROBONOID, new ResourceLocation("ke2:entity.mech.robonoid"), event);
		Ke2Sounds.registerSound(Ke2Sounds.MECH_PRISM, new ResourceLocation("ke2:entity.mech.prism"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_GENERIC, new ResourceLocation("ke2:entity.gem.generic"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_AGATE, new ResourceLocation("ke2:entity.gem.agate"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_AMETHYST, new ResourceLocation("ke2:entity.gem.amethyst"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_AQUA_AURA_QUARTZ, new ResourceLocation("ke2:entity.gem.aqua_aura_quartz"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_AQUAMARINE, new ResourceLocation("ke2:entity.gem.aquamarine"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_BISMUTH, new ResourceLocation("ke2:entity.gem.bismuth"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_BLUE_DIAMOND, new ResourceLocation("ke2:entity.gem.blue_diamond"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_CARNELIAN, new ResourceLocation("ke2:entity.gem.carnelian"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_CITRINE, new ResourceLocation("ke2:entity.gem.citrine"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_CLUSTER, new ResourceLocation("ke2:entity.gem.cluster"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_CORAL, new ResourceLocation("ke2:entity.gem.coral"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_DEMANTOID, new ResourceLocation("ke2:entity.gem.demantoid"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_DESERT_GLASS, new ResourceLocation("ke2:entity.gem.desert_glass"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_EMERALD, new ResourceLocation("ke2:entity.gem.emerald"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_ENDER_PEARL, new ResourceLocation("ke2:entity.gem.ender_pearl"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_HESSONITE, new ResourceLocation("ke2:entity.gem.hessonite"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_HIDDENITE, new ResourceLocation("ke2:entity.gem.hiddenite"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_JADE, new ResourceLocation("ke2:entity.gem.jade"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_JASPER, new ResourceLocation("ke2:entity.gem.jasper"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_KUNZITE, new ResourceLocation("ke2:entity.gem.kunzite"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_LAPIS_LAZULI, new ResourceLocation("ke2:entity.gem.lapis_lazuli"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_LARIMAR, new ResourceLocation("ke2:entity.gem.larimar"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_MELANITE, new ResourceLocation("ke2:entity.gem.melanite"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_MOTHER_OF_PEARL, new ResourceLocation("ke2:entity.gem.mother_of_pearl"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_NEPHRITE, new ResourceLocation("ke2:entity.gem.nephrite"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_PEARL, new ResourceLocation("ke2:entity.gem.pearl"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_PEBBLE, new ResourceLocation("ke2:entity.gem.pebble"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_PERIDOT, new ResourceLocation("ke2:entity.gem.peridot"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_PINK_DIAMOND, new ResourceLocation("ke2:entity.gem.pink_diamond"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_PYRITE, new ResourceLocation("ke2:entity.gem.pyrite"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_PYROPE, new ResourceLocation("ke2:entity.gem.pyrope"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_ROSE_QUARTZ, new ResourceLocation("ke2:entity.gem.rose_quartz"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_RUBY, new ResourceLocation("ke2:entity.gem.ruby"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_RUTILE, new ResourceLocation("ke2:entity.gem.rutile"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_SAPPHIRE, new ResourceLocation("ke2:entity.gem.sapphire"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_SNOWFLAKE_OBSIDIAN, new ResourceLocation("ke2:entity.gem.snowflake_obsidian"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_TOPAZ, new ResourceLocation("ke2:entity.gem.topaz"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_WATERMELON_TOURMALINE, new ResourceLocation("ke2:entity.gem.watermelon_tourmaline"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_WHITE_DIAMOND, new ResourceLocation("ke2:entity.gem.white_diamond"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_YELLOW_DIAMOND, new ResourceLocation("ke2:entity.gem.yellow_diamond"), event);
		Ke2Sounds.registerSound(Ke2Sounds.GEM_ZIRCON, new ResourceLocation("ke2:entity.gem.zircon"), event);
	}

	private static void registerSound(SoundEvent sound, ResourceLocation location, RegistryEvent.Register<SoundEvent> event) {
		sound.setRegistryName(location);
		event.getRegistry().register(sound);
	}
}
