package mod.kagic.init;

import java.util.ArrayList;
import java.util.HashMap;

import mod.kagic.blocks.BlockCarbonite;
import mod.kagic.blocks.BlockDrainBlock;
import mod.kagic.blocks.BlockDrainLily;
import mod.kagic.blocks.BlockGemSeed;
import mod.kagic.blocks.BlockMagicMoss;
import mod.kagic.blocks.BlockMossRose;
import mod.kagic.blocks.BlockWailingStone;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.oredict.OreDictionary;

public class AmBlocks {
	public static final HashMap<String, Item> DICTS = new HashMap<String, Item>();
	public static final HashMap<Item, String[]> META = new HashMap<Item, String[]>();
	public static final ArrayList<Item> ITEMS = new ArrayList<Item>();
	
	public static final BlockWailingStone WAILING_STONE = new BlockWailingStone();
	public static final BlockGemSeed GEM_SEED = new BlockGemSeed();
	
	public static final BlockMagicMoss MAGIC_MOSS = new BlockMagicMoss();
	public static final BlockMossRose MOSS_ROSE = new BlockMossRose();
	
	public static final BlockDrainLily VALLEY_DRAIN_LILY = new BlockDrainLily("valley");
	public static final BlockDrainLily DESERT_DRAIN_LILY = new BlockDrainLily("desert");
	public static final BlockDrainLily ALPINE_DRAIN_LILY = new BlockDrainLily("alpine");
	public static final BlockDrainLily NETHER_DRAIN_LILY = new BlockDrainLily("nether");
	
	public static final BlockDrainBlock LIGHT_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(false, "purple", 0);
	public static final BlockDrainBlock BANDED_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(false, "purple", 1);
	public static final BlockDrainBlock DARK_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(false, "purple", 2);
	public static final BlockDrainBlock ERODED_PURPLE_DRAIN_BLOCK = new BlockDrainBlock(true, "purple", 3);
	public static final BlockDrainBlock LIGHT_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(false, "orange", 0);
	public static final BlockDrainBlock BANDED_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(false, "orange", 1);
	public static final BlockDrainBlock DARK_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(false, "orange", 2);
	public static final BlockDrainBlock ERODED_ORANGE_DRAIN_BLOCK = new BlockDrainBlock(true, "orange", 3);
	public static final BlockDrainBlock LIGHT_BLUE_DRAIN_BLOCK = new BlockDrainBlock(false, "blue", 0);
	public static final BlockDrainBlock BANDED_BLUE_DRAIN_BLOCK = new BlockDrainBlock(false, "blue", 1);
	public static final BlockDrainBlock DARK_BLUE_DRAIN_BLOCK = new BlockDrainBlock(false, "blue", 2);
	public static final BlockDrainBlock ERODED_BLUE_DRAIN_BLOCK = new BlockDrainBlock(true, "blue", 3);
	public static final BlockDrainBlock LIGHT_RED_DRAIN_BLOCK = new BlockDrainBlock(false, "red", 0);
	public static final BlockDrainBlock BANDED_RED_DRAIN_BLOCK = new BlockDrainBlock(false, "red", 1);
	public static final BlockDrainBlock DARK_RED_DRAIN_BLOCK = new BlockDrainBlock(false, "red", 2);
	public static final BlockDrainBlock ERODED_RED_DRAIN_BLOCK = new BlockDrainBlock(true, "red", 3);

	public static final BlockCarbonite WHITE_CARBONITE = new BlockCarbonite(AmGems.BASIC_WHITE);
	public static final BlockCarbonite WHITE_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_WHITE);
	public static final BlockCarbonite WHITE_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_WHITE);
	public static final BlockCarbonite WHITE_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_WHITE);
	public static final BlockCarbonite ORANGE_CARBONITE = new BlockCarbonite(AmGems.BASIC_ORANGE);
	public static final BlockCarbonite ORANGE_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_ORANGE);
	public static final BlockCarbonite ORANGE_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_ORANGE);
	public static final BlockCarbonite ORANGE_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_ORANGE);
	public static final BlockCarbonite MAGENTA_CARBONITE = new BlockCarbonite(AmGems.BASIC_MAGENTA);
	public static final BlockCarbonite MAGENTA_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_MAGENTA);
	public static final BlockCarbonite MAGENTA_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_MAGENTA);
	public static final BlockCarbonite MAGENTA_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_MAGENTA);
	public static final BlockCarbonite LIGHTBLUE_CARBONITE = new BlockCarbonite(AmGems.BASIC_LIGHTBLUE);
	public static final BlockCarbonite LIGHTBLUE_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_LIGHTBLUE);
	public static final BlockCarbonite LIGHTBLUE_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_LIGHTBLUE);
	public static final BlockCarbonite LIGHTBLUE_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_LIGHTBLUE);
	public static final BlockCarbonite YELLOW_CARBONITE = new BlockCarbonite(AmGems.BASIC_YELLOW);
	public static final BlockCarbonite YELLOW_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_YELLOW);
	public static final BlockCarbonite YELLOW_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_YELLOW);
	public static final BlockCarbonite YELLOW_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_YELLOW);
	public static final BlockCarbonite LIME_CARBONITE = new BlockCarbonite(AmGems.BASIC_LIME);
	public static final BlockCarbonite LIME_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_LIME);
	public static final BlockCarbonite LIME_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_LIME);
	public static final BlockCarbonite LIME_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_LIME);
	public static final BlockCarbonite PINK_CARBONITE = new BlockCarbonite(AmGems.BASIC_PINK);
	public static final BlockCarbonite PINK_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_PINK);
	public static final BlockCarbonite PINK_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_PINK);
	public static final BlockCarbonite PINK_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_PINK);
	public static final BlockCarbonite GRAY_CARBONITE = new BlockCarbonite(AmGems.BASIC_GRAY);
	public static final BlockCarbonite GRAY_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_GRAY);
	public static final BlockCarbonite GRAY_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_GRAY);
	public static final BlockCarbonite GRAY_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_GRAY);
	public static final BlockCarbonite SILVER_CARBONITE = new BlockCarbonite(AmGems.BASIC_SILVER);
	public static final BlockCarbonite SILVER_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_SILVER);
	public static final BlockCarbonite SILVER_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_SILVER);
	public static final BlockCarbonite SILVER_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_SILVER);
	public static final BlockCarbonite CYAN_CARBONITE = new BlockCarbonite(AmGems.BASIC_CYAN);
	public static final BlockCarbonite CYAN_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_CYAN);
	public static final BlockCarbonite CYAN_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_CYAN);
	public static final BlockCarbonite CYAN_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_CYAN);
	public static final BlockCarbonite PURPLE_CARBONITE = new BlockCarbonite(AmGems.BASIC_PURPLE);
	public static final BlockCarbonite PURPLE_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_PURPLE);
	public static final BlockCarbonite PURPLE_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_PURPLE);
	public static final BlockCarbonite PURPLE_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_PURPLE);
	public static final BlockCarbonite BLUE_CARBONITE = new BlockCarbonite(AmGems.BASIC_BLUE);
	public static final BlockCarbonite BLUE_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_BLUE);
	public static final BlockCarbonite BLUE_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_BLUE);
	public static final BlockCarbonite BLUE_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_BLUE);
	public static final BlockCarbonite BROWN_CARBONITE = new BlockCarbonite(AmGems.BASIC_BROWN);
	public static final BlockCarbonite BROWN_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_BROWN);
	public static final BlockCarbonite BROWN_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_BROWN);
	public static final BlockCarbonite BROWN_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_BROWN);
	public static final BlockCarbonite GREEN_CARBONITE = new BlockCarbonite(AmGems.BASIC_GREEN);
	public static final BlockCarbonite GREEN_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_GREEN);
	public static final BlockCarbonite GREEN_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_GREEN);
	public static final BlockCarbonite GREEN_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_GREEN);
	public static final BlockCarbonite RED_CARBONITE = new BlockCarbonite(AmGems.BASIC_RED);
	public static final BlockCarbonite RED_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_RED);
	public static final BlockCarbonite RED_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_RED);
	public static final BlockCarbonite RED_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_RED);
	public static final BlockCarbonite BLACK_CARBONITE = new BlockCarbonite(AmGems.BASIC_BLACK);
	public static final BlockCarbonite BLACK_CARBONITE_OFF = new BlockCarbonite(false, AmGems.BASIC_BLACK);
	public static final BlockCarbonite BLACK_CARBONITE_ON = new BlockCarbonite(true, AmGems.BASIC_BLACK);
	public static final BlockCarbonite BLACK_DECORATIVE_CARBONITE = new BlockCarbonite(AmGems.BASIC_BLACK);
	
	public static void register(RegistryEvent.Register<Block> event) {
		registerBlock(WAILING_STONE, new ResourceLocation("kagic:wailing_stone"), event);
		registerBlock(GEM_SEED, new ResourceLocation("kagic:gem_seed"), event);
		registerBlock(MAGIC_MOSS, new ResourceLocation("kagic:magic_moss"), event);
		registerBlock(MOSS_ROSE, new ResourceLocation("kagic:moss_rose"), event);
		registerBlock(VALLEY_DRAIN_LILY, new ResourceLocation("kagic:valley_drain_lily"), event);
		registerBlock(DESERT_DRAIN_LILY, new ResourceLocation("kagic:desert_drain_lily"), event);
		registerBlock(ALPINE_DRAIN_LILY, new ResourceLocation("kagic:alpine_drain_lily"), event);
		registerBlock(NETHER_DRAIN_LILY, new ResourceLocation("kagic:nether_drain_lily"), event);
		registerBlock(LIGHT_PURPLE_DRAIN_BLOCK, new ResourceLocation("kagic:light_purple_drain_block"), event);
		registerBlock(BANDED_PURPLE_DRAIN_BLOCK, new ResourceLocation("kagic:banded_purple_drain_block"), event);
		registerBlock(DARK_PURPLE_DRAIN_BLOCK, new ResourceLocation("kagic:dark_purple_drain_block"), event);
		registerBlock(ERODED_PURPLE_DRAIN_BLOCK, new ResourceLocation("kagic:eroded_purple_drain_block"), event);
		registerBlock(LIGHT_ORANGE_DRAIN_BLOCK, new ResourceLocation("kagic:light_orange_drain_block"), event);
		registerBlock(BANDED_ORANGE_DRAIN_BLOCK, new ResourceLocation("kagic:banded_orange_drain_block"), event);
		registerBlock(DARK_ORANGE_DRAIN_BLOCK, new ResourceLocation("kagic:dark_orange_drain_block"), event);
		registerBlock(ERODED_ORANGE_DRAIN_BLOCK, new ResourceLocation("kagic:eroded_orange_drain_block"), event);
		registerBlock(LIGHT_BLUE_DRAIN_BLOCK, new ResourceLocation("kagic:light_blue_drain_block"), event);
		registerBlock(BANDED_BLUE_DRAIN_BLOCK, new ResourceLocation("kagic:banded_blue_drain_block"), event);
		registerBlock(DARK_BLUE_DRAIN_BLOCK, new ResourceLocation("kagic:dark_blue_drain_block"), event);
		registerBlock(ERODED_BLUE_DRAIN_BLOCK, new ResourceLocation("kagic:eroded_blue_drain_block"), event);
		registerBlock(LIGHT_RED_DRAIN_BLOCK, new ResourceLocation("kagic:light_red_drain_block"), event);
		registerBlock(BANDED_RED_DRAIN_BLOCK, new ResourceLocation("kagic:banded_red_drain_block"), event);
		registerBlock(DARK_RED_DRAIN_BLOCK, new ResourceLocation("kagic:dark_red_drain_block"), event);
		registerBlock(ERODED_RED_DRAIN_BLOCK, new ResourceLocation("kagic:eroded_red_drain_block"), event);
		registerBlock(WHITE_CARBONITE, new ResourceLocation("kagic:white_carbonite"), event);
		registerBlock(WHITE_CARBONITE_OFF, new ResourceLocation("kagic:white_carbonite_off"), event);
		registerBlock(WHITE_CARBONITE_ON, new ResourceLocation("kagic:white_carbonite_on"), event);
		registerBlock(WHITE_DECORATIVE_CARBONITE, new ResourceLocation("kagic:white_decorative_carbonite"), event);
		registerBlock(ORANGE_CARBONITE, new ResourceLocation("kagic:orange_carbonite"), event);
		registerBlock(ORANGE_CARBONITE_OFF, new ResourceLocation("kagic:orange_carbonite_off"), event);
		registerBlock(ORANGE_CARBONITE_ON, new ResourceLocation("kagic:orange_carbonite_on"), event);
		registerBlock(ORANGE_DECORATIVE_CARBONITE, new ResourceLocation("kagic:orange_decorative_carbonite"), event);
		registerBlock(MAGENTA_CARBONITE, new ResourceLocation("kagic:magenta_carbonite"), event);
		registerBlock(MAGENTA_CARBONITE_OFF, new ResourceLocation("kagic:magenta_carbonite_off"), event);
		registerBlock(MAGENTA_CARBONITE_ON, new ResourceLocation("kagic:magenta_carbonite_on"), event);
		registerBlock(MAGENTA_DECORATIVE_CARBONITE, new ResourceLocation("kagic:magenta_decorative_carbonite"), event);
		registerBlock(LIGHTBLUE_CARBONITE, new ResourceLocation("kagic:lightblue_carbonite"), event);
		registerBlock(LIGHTBLUE_CARBONITE_OFF, new ResourceLocation("kagic:lightblue_carbonite_off"), event);
		registerBlock(LIGHTBLUE_CARBONITE_ON, new ResourceLocation("kagic:lightblue_carbonite_on"), event);
		registerBlock(LIGHTBLUE_DECORATIVE_CARBONITE, new ResourceLocation("kagic:lightblue_decorative_carbonite"), event);
		registerBlock(YELLOW_CARBONITE, new ResourceLocation("kagic:yellow_carbonite"), event);
		registerBlock(YELLOW_CARBONITE_OFF, new ResourceLocation("kagic:yellow_carbonite_off"), event);
		registerBlock(YELLOW_CARBONITE_ON, new ResourceLocation("kagic:yellow_carbonite_on"), event);
		registerBlock(YELLOW_DECORATIVE_CARBONITE, new ResourceLocation("kagic:yellow_decorative_carbonite"), event);
		registerBlock(LIME_CARBONITE, new ResourceLocation("kagic:lime_carbonite"), event);
		registerBlock(LIME_CARBONITE_OFF, new ResourceLocation("kagic:lime_carbonite_off"), event);
		registerBlock(LIME_CARBONITE_ON, new ResourceLocation("kagic:lime_carbonite_on"), event);
		registerBlock(LIME_DECORATIVE_CARBONITE, new ResourceLocation("kagic:lime_decorative_carbonite"), event);
		registerBlock(PINK_CARBONITE, new ResourceLocation("kagic:pink_carbonite"), event);
		registerBlock(PINK_CARBONITE_OFF, new ResourceLocation("kagic:pink_carbonite_off"), event);
		registerBlock(PINK_CARBONITE_ON, new ResourceLocation("kagic:pink_carbonite_on"), event);
		registerBlock(PINK_DECORATIVE_CARBONITE, new ResourceLocation("kagic:pink_decorative_carbonite"), event);
		registerBlock(GRAY_CARBONITE, new ResourceLocation("kagic:gray_carbonite"), event);
		registerBlock(GRAY_CARBONITE_OFF, new ResourceLocation("kagic:gray_carbonite_off"), event);
		registerBlock(GRAY_CARBONITE_ON, new ResourceLocation("kagic:gray_carbonite_on"), event);
		registerBlock(GRAY_DECORATIVE_CARBONITE, new ResourceLocation("kagic:gray_decorative_carbonite"), event);
		registerBlock(SILVER_CARBONITE, new ResourceLocation("kagic:silver_carbonite"), event);
		registerBlock(SILVER_CARBONITE_OFF, new ResourceLocation("kagic:silver_carbonite_off"), event);
		registerBlock(SILVER_CARBONITE_ON, new ResourceLocation("kagic:silver_carbonite_on"), event);
		registerBlock(SILVER_DECORATIVE_CARBONITE, new ResourceLocation("kagic:silver_decorative_carbonite"), event);
		registerBlock(CYAN_CARBONITE, new ResourceLocation("kagic:cyan_carbonite"), event);
		registerBlock(CYAN_CARBONITE_OFF, new ResourceLocation("kagic:cyan_carbonite_off"), event);
		registerBlock(CYAN_CARBONITE_ON, new ResourceLocation("kagic:cyan_carbonite_on"), event);
		registerBlock(CYAN_DECORATIVE_CARBONITE, new ResourceLocation("kagic:cyan_decorative_carbonite"), event);
		registerBlock(PURPLE_CARBONITE, new ResourceLocation("kagic:purple_carbonite"), event);
		registerBlock(PURPLE_CARBONITE_OFF, new ResourceLocation("kagic:purple_carbonite_off"), event);
		registerBlock(PURPLE_CARBONITE_ON, new ResourceLocation("kagic:purple_carbonite_on"), event);
		registerBlock(PURPLE_DECORATIVE_CARBONITE, new ResourceLocation("kagic:purple_decorative_carbonite"), event);
		registerBlock(BLUE_CARBONITE, new ResourceLocation("kagic:blue_carbonite"), event);
		registerBlock(BLUE_CARBONITE_OFF, new ResourceLocation("kagic:blue_carbonite_off"), event);
		registerBlock(BLUE_CARBONITE_ON, new ResourceLocation("kagic:blue_carbonite_on"), event);
		registerBlock(BLUE_DECORATIVE_CARBONITE, new ResourceLocation("kagic:blue_decorative_carbonite"), event);
		registerBlock(BROWN_CARBONITE, new ResourceLocation("kagic:brown_carbonite"), event);
		registerBlock(BROWN_CARBONITE_OFF, new ResourceLocation("kagic:brown_carbonite_off"), event);
		registerBlock(BROWN_CARBONITE_ON, new ResourceLocation("kagic:brown_carbonite_on"), event);
		registerBlock(BROWN_DECORATIVE_CARBONITE, new ResourceLocation("kagic:brown_decorative_carbonite"), event);
		registerBlock(GREEN_CARBONITE, new ResourceLocation("kagic:green_carbonite"), event);
		registerBlock(GREEN_CARBONITE_OFF, new ResourceLocation("kagic:green_carbonite_off"), event);
		registerBlock(GREEN_CARBONITE_ON, new ResourceLocation("kagic:green_carbonite_on"), event);
		registerBlock(GREEN_DECORATIVE_CARBONITE, new ResourceLocation("kagic:green_decorative_carbonite"), event);
		registerBlock(RED_CARBONITE, new ResourceLocation("kagic:red_carbonite"), event);
		registerBlock(RED_CARBONITE_OFF, new ResourceLocation("kagic:red_carbonite_off"), event);
		registerBlock(RED_CARBONITE_ON, new ResourceLocation("kagic:red_carbonite_on"), event);
		registerBlock(RED_DECORATIVE_CARBONITE, new ResourceLocation("kagic:red_decorative_carbonite"), event);
		registerBlock(BLACK_CARBONITE, new ResourceLocation("kagic:black_carbonite"), event);
		registerBlock(BLACK_CARBONITE_OFF, new ResourceLocation("kagic:black_carbonite_off"), event);
		registerBlock(BLACK_CARBONITE_ON, new ResourceLocation("kagic:black_carbonite_on"), event);
		registerBlock(BLACK_DECORATIVE_CARBONITE, new ResourceLocation("kagic:black_decorative_carbonite"), event);
	}
	public static void registerOre(Block block, ResourceLocation location, RegistryEvent.Register<Block> event, String... ores) {
		registerBlock(block, location, event);
		for (int i = 0; i < ores.length; ++i) {
			OreDictionary.registerOre(ores[i], ITEMS.get(ITEMS.size() - 1));
		}
	}
	public static void registerBlock(Block block, ResourceLocation location, RegistryEvent.Register<Block> event, String...meta) {
		event.getRegistry().register(block.setRegistryName(location));
		ITEMS.add(new ItemBlock(block).setRegistryName(location));
	}
}